### PR TITLE
Add MIT License to the project

### PR DESCRIPTION
**Pull request by garethrees**
I'm looking to use this gem  but noticed that there's no LICENSE.md file. Would you consider releasing this under the MIT licence please?

Thanks

### CODE REVIEW

**Comment by munen** [comment]
@garethrees Thank you very much for looking into using gh-events^^ From experience, I hope you will be able to make as good use of it as we do^^

Regarding the license, thank you very much for noticing and bringing it up :pray:  We're usually releasing our projects as free software (https://200ok.ch/floss.html). Since this project is a library, I'd propose the [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html).

@branch14: You are the original author and main contributor. Of course, I'll happily leave this up to you! Just wanting to quickly give an answer to the first contributor(;

**Comment by garethrees** [comment]
> Since this project is a library, I'd propose the LGPL.

Works for me – I just suggested a default to make it easier to just merge if you were happy.

**Comment by munen** [comment]
@garethrees Nice!

Are you blocked from using `gh-events` for the moment due to the lack of a license? If so and if LGPL works for you, I can add it right away. If Phil decides to go with a less strict license (like MIT), it would be his prerogative to change it in the near future. In any case, that wouldn't give you fewer options to integrate it into your system, so it shouldn't affect you negatively.

**Comment by garethrees** [comment]
Nah take your time, it's just for personal use right now. I just wanted to know that if I wanted to make changes / contribute, that they'd be under an acceptable license.

**Comment by munen** [comment]
> Nah take your time, it's just for personal use right now. 

:+1: 

> I just wanted to know that if I wanted to make changes / contribute, that they'd be under an acceptable license.

PRs are welcome any time! We'd be happy if the parser get's a little traction like its sister project organice (https://github.com/200ok-ch/organice/) which runs quite nicely as a community project with multiple maintainers by now^^

**Comment by branch14** [comment]
@garethrees Thx for the PR. MIT is totally fine.

**Pull request merged**
